### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Thanks for your amazing work!
Here is a proposal of translation in French (see #4 ).
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by erpe** [comment]
oh - thanks for your PR, 
i'll have a look at it asap - please stay calm, i'm quite busy these days...

**Comment by ghost** [comment]
Hello! Do you have some time to review this pull request?

**Comment by erpe** [comment]
hi @Anne017  would you like to take over this repository?

**Comment by ghost** [comment]
Hi @erpe , unfortunately I am essentially a translator, not a developer.
So I am not sure to be very helpful eventually...

**Pull request closed without merging**
